- src/components/CommonButton/index.tsx
- src/page-components/Home/SelectTokenModal/index.tsx
- src/page-components/Home/SelectTokenModal/styles.module.less
Search filter for token popup and no data found message
> feature/EB-24401739: Search filter for token popup and no data found message

- src/components/Header/index.tsx
- src/components/Header/styles.module.less
Add close icon for mobile menu
> feature/EB-24403063: Add close icon for mobile menu

- src/page-components/Home/ChangeIcon/index.tsx
> feature/EB-24383219: Remove swap animation feature 

- src/i18n/languages/en.json
- src/i18n/languages/zh.json
- src/page-components/Home/Card/CheckBoxInputRow.tsx
- src/page-components/Home/Card/styles.module.less
Help icon with tooltip on “Send to the recipient wallet address”
> feature/EB-24403302: Help icon with tooltip on “Send to the recipient wallet address”

- package.json
- yarn.lock
portkey/onboarding version upgrade to ^2.0.0-alpha.26
> feature/EB-3004550541: portkey/onboarding version upgrade

- src/contexts/usePortkey/constants.ts
- src/contexts/usePortkey/provider.tsx
when disable or uninstall portkey v1，then connect the wallet by portkey v1，prompt：connection error：provider init error
> fix: eb_3010422529 Install and Disable portkey app issue

- src/components/Network/Network.tsx
- src/i18n/languages/en.json
- src/i18n/languages/zh.json
- src/page-components/Home/ActionButton/index.tsx
- src/page-components/Home/index.tsx
- src/utils/chain.ts
Unsupported evm network on wallet
> feature/EB-3000131156: Unsupported evm network on wallet

- src/components/Network/Network.tsx
- src/constants/wallets.ts
- src/i18n/languages/en.json
- src/i18n/languages/zh.json
- src/page-components/Home/ActionButton/index.tsx
- src/page-components/Home/index.tsx
- src/utils/chain.ts
Code revert of coin base wallet issue and wrong network issue
> feature/EB-3000131432: Code revert of coin base wallet issue and wrong network issue

- package.json
- yarn.lock
> feature/EB-3004550541: Update porteky v1 and v2 name

- src/constants/mainnet/index.ts
Updated mainnet network type to "MAINNET"
> feature/EB-3004550541: Updated mainnet network type to "MAINNET"

- src/contexts/usePortkey/provider.tsx
- src/contexts/usePortkey/types.ts
Portkey temporary workaround fix
> feature/EB-3004550541: Portkey temporary workaround fix

- src/components/Network/Network.tsx
- src/constants/chainInfo.ts
- src/constants/mainnet/index.ts
- src/constants/platform/AELF_Test.ts
- src/constants/platform/TRON_Nile_Testnet.ts
- src/constants/platform/tDVV_Test.ts
- src/constants/testnet/index.ts
- src/constants/testnet/tokenWhitelist.json
- src/contracts/tron.ts
- src/hooks/useContract.ts
- src/modals/AccountModal/AccountCard.tsx
- src/page-components/Home/ActionButton/index.tsx
- src/page-components/Home/Card/WalletRow.tsx
- src/page-components/Home/useLimitAmountModal/index.tsx
- src/utils/contract.ts
- src/utils/crossChain.ts
- src/utils/index.ts
- src/utils/network.ts
- yarn.lock
> feature/EB-3010934420: Bridge out implementation

- src/constants/misc.ts
- src/page-components/Home/ActionButton/index.tsx
- src/page-components/Home/Card/components.tsx
- src/page-components/Home/Card/index.tsx
- src/page-components/Home/History/columns.tsx
- src/page-components/Home/LimitAmountDescModal/columns.tsx
- src/page-components/Home/SelectTokenModal/index.tsx
- src/utils/token.ts
1. Symbol display optimization. close #121
> Symbol display optimization

- .github/workflows/mainnet-package.yaml
- src/components/PageHead/index.tsx
- src/i18n/languages/en.json
- src/i18n/languages/zh.json
- src/page-components/Home/index.tsx
Improve the SEO and TDK of the website. close #136
> Improve the SEO and TDK of the website.

- .github/workflows/mainnet-package.yaml
- src/constants/mainnet/tokenWhitelist.json
- src/constants/misc.ts
- src/constants/testnet/tokenWhitelist.json
- src/contexts/useWallet/actions.ts
- src/contexts/useWallet/index.tsx
- src/page-components/Home/Card/WalletRow.tsx
- src/utils/contract.ts
Support Base chain AGENT cross-chain. close #140
> Support Base chain AGENT cross-chain.

- src/constants/misc.ts
Support Base chain AGENT cross-chain. #140
> Support Base chain AGENT cross-chain. 

- package.json
- src/api/utils.ts
- src/constants/index.ts
- src/constants/mainnet/index.ts
- src/constants/mainnet/tokenWhitelist.json
- src/constants/platform/AELF.ts
- src/constants/platform/AELF_Test.ts
- src/constants/platform/tDVV.ts
- src/constants/platform/tDVW_Test.ts
- src/constants/testnet/index.ts
- src/page-components/Home/index.tsx
Add token pool , support base chain tokens such as USDC and ETH. close #148
> Add token pool , support base chain tokens such as USDC and ETH.

- src/modals/WalletsModal/index.tsx
- src/styles/globals.less
> Fix: dependencies of useMemo

- src/api/list.ts
- src/contexts/useWallet/utils.ts
- src/modals/WalletsModal/styles.module.less
- src/page-components/Bridge/ActionButton/index.tsx
- src/page-components/Bridge/CheckBoxInputRow/index.tsx
- src/page-components/Transactions/columns.tsx
1. Fix: eslint
2. Style: adjust wallets modal body width
> Fix: eslint

- src/components/Header/index.tsx
- src/page-components/Bridge/ActionButton/index.tsx
- src/page-components/Bridge/AmountRow/index.tsx
- src/utils/input.ts
> Fix: action button

- src/page-components/Transactions/index.tsx
> Fix: transactions

- src/pages/_app.tsx
> Fix: header in portkey

- src/components/WalletList/index.tsx
- src/page-components/Bridge/ActionButton/index.tsx
1. Fix: hide MetaMask on mobile devices
2. Fix: approve
> Fix: approve

- src/components/CommonTable/index.tsx
- src/components/Header/index.tsx
- src/i18n/languages/en.json
- src/i18n/languages/zh.json
- src/page-components/Bridge/BridgeHeader/index.tsx
- src/page-components/Transactions/columns.tsx
- src/page-components/Transactions/index.tsx
1. Chore: adjust style and text
> Chore: adjust style and text

- src/page-components/Transactions/index.tsx
> Fix: transactions data

- src/page-components/TermsOfService/index.tsx
> Chore: adjust text

- src/components/MainContentHeader/index.tsx
- src/components/WalletList/index.tsx
- src/components/WalletList/styles.module.less
- src/modals/AccountModal/AccountCard.tsx
- src/page-components/Bridge/CheckBoxInputRow/index.tsx
- src/page-components/Bridge/SelectTokenModal/styles.module.less
- src/page-components/PrivacyPolicy/styles.module.less
- src/page-components/TermsOfService/styles.module.less
- src/page-components/Transactions/index.tsx
- src/styles/common/commonModal.less
1. Adjust transactions data and styles
> Adjust transactions data and styles

- src/page-components/Transactions/components.tsx
- src/page-components/Transactions/styles.module.less
> Style: adjust pagination

- src/components/Header/index.tsx
- src/components/MainContentHeader/index.tsx
- src/components/Nav/index.tsx
- src/components/Network/Network.tsx
- src/page-components/Bridge/ActionButton/index.tsx
- src/page-components/Bridge/AmountRow/TokenSelect/index.tsx
- src/page-components/Bridge/CheckBoxInputRow/index.tsx
- src/page-components/Transactions/columns.tsx
1. Chore: commonImage priority
> Chore: commonImage priority

- src/constants/link.ts
> Chore: remove discord link

- .github/workflows/test.yml
Chore: remove build step from github actions
> Chore: remove build step from github actions

- src/api/utils.ts
Fix: remove x-csrf-token header to resolve CORS issues​. #166
> Fix: remove x-csrf-token header to resolve CORS issues​

- src/page-components/Transactions/index.tsx
Feat: hide all transactions in portkey
> Feat: hide all transactions in portkey

- src/components/Header/index.tsx
> Hide coinbase icon in portkey

- src/page-components/PrivacyPolicy/styles.module.less
- src/page-components/TermsOfService/styles.module.less
- src/styles/globals.less
> Style: adjust bottom

- src/utils/network.ts
> Chore: adjust error text

- src/components/Header/index.tsx
- src/i18n/languages/zh.json
- src/page-components/Bridge/ActionButton/index.tsx
Fix: homogeneous connect modal
> Fix: homogeneous connect modal

- src/components/Header/index.tsx
- src/components/WalletList/index.tsx
- src/hooks/web3.ts
- src/i18n/languages/zh.json
- src/page-components/Bridge/ActionButton/index.tsx
- src/page-components/PrivacyPolicy/styles.module.less
- src/page-components/TermsOfService/styles.module.less
- src/page-components/Transactions/index.tsx
- src/styles/globals.less
- src/utils/network.ts
> UI revamp adjust

- src/styles/common/commonModal.less
- src/styles/globals.less
Fix: page height issues caused by browser address bar on mobile devices. close #188
> Fix: page height issues caused by browser address bar on mobile devices

- src/constants/mainnet/index.ts
- src/constants/testnet/index.ts
- src/page-components/Bridge/Info/index.tsx
> Update indexer v2

- src/constants/mainnet/index.ts
- src/constants/testnet/index.ts
Update aefinder v2. closed #196
> Update aefinder v2.

- src/constants/aelf.ts
- src/constants/index.ts
- src/constants/mainnet/index.ts
- src/constants/testnet/index.ts
- src/utils/aelfUtils.tsx
Update Indexer URL. Close #209
> Update Indexer URL.

- src/page-components/ListingApplication/TokenInformation/index.tsx
Modify token liquidity fetching order in listing application. #216
> Modify token liquidity fetching order in listing application.

- src/page-components/Pools/Pool/RemovePool/index.tsx
- src/utils/pools.tsx
Support Token Issuance and Management on aelf Chain and EVM Integration. closed #212 
Deploy aelf chain token issuance and eBridge integration feature. closed #213
> Support Token Issuance and Management on aelf Chain and EVM Integration.

- .github/workflows/nextLint.yml
- src/page-components/Pools/Pool/AddPool/index.tsx
- src/page-components/Pools/Pool/index.tsx
- src/page-components/Pools/Pool/styles.module.less
Fix balance fetching and styling issues on the Add Pool page. closed #228
> Fix balance fetching and styling issues on the Add Pool page.

- .github/workflows/codecov.yml
- .github/workflows/unit-test.yaml
- src/constants/link.ts
- src/modals/WalletsModal/index.tsx
- src/pages/privacy-policy.tsx
- src/pages/terms-of-service.tsx
- src/utils/__tests__/aelfAuthToken.test.ts
- src/utils/aelfAuthToken.ts
Update Terms of Service and Privacy Policy Links. closed #232
> Update Terms of Service and Privacy Policy Links.

- src/constants/storages.ts
Support Bi-directional Cross-chain Between TON and aelf. #234
> Support Bi-directional Cross-chain Between TON and aelf.

- .github/workflows/mainnet-package.yaml
- .github/workflows/testnet-package.yaml
integrate the Atherlink EVM oracle. #239
> integrate the Atherlink EVM oracle.
